name: event_dispatcher
version: 1.2.1
author: samrg472 <samrg472@gmail.com>
description: An easy to use event dispatching API
homepage: https://github.com/samrg472/event_dispatcher.dart
environment:
  sdk: ">=1.8.0"
